import { Type, type Static, type TSchema } from 'typebox';
import { Currency } from './contracts.js';
import { RecurrenceDate } from './recurrence-contracts.js';
const strict = { additionalProperties: false }, Id = Type.String({ format: 'uuid' }), Instant = Type.String({ format: 'date-time' });
const Nullable = <T extends TSchema>(s:T) => Type.Union([s, Type.Null()]);
const Minor = Type.String({ pattern: '^(0|[1-9][0-9]*)$', maxLength: 19 });
const Aggregate = Type.String({ pattern: '^(0|[1-9][0-9]*)$' }), Signed = Type.String({ pattern: '^-?(0|[1-9][0-9]*)$' });
export const NetWorthKind = Type.Union([Type.Literal('ASSET'),Type.Literal('LIABILITY')]);
export const NetWorthStatus = Type.Union([Type.Literal('ACTIVE'),Type.Literal('ARCHIVED')]);
export const NetWorthCategory = Type.Union([Type.Literal('PROPERTY'),Type.Literal('VEHICLE'),Type.Literal('BUSINESS'),Type.Literal('VALUABLE'),Type.Literal('OTHER'),Type.Literal('MORTGAGE'),Type.Literal('LOAN'),Type.Literal('FINANCING')]);
const metadata = { name: Type.String({ minLength: 1,maxLength: 100 }), description: Nullable(Type.String({ maxLength: 1000 })), category: NetWorthCategory };
export const NetWorthItemInput = Type.Object({ ...metadata, description: Type.Optional(metadata.description), kind: NetWorthKind, currency: Currency, initialValueMinor: Minor, valuationDate: RecurrenceDate, valuationNote: Type.Optional(Nullable(Type.String({ maxLength: 1000 }))) },strict);
export const NetWorthItemPatch = Type.Partial(Type.Object(metadata),{...strict,minProperties:1});
export const NetWorthValuationInput = Type.Object({ valueMinor: Minor, valuationDate: RecurrenceDate, note: Type.Optional(Nullable(Type.String({ maxLength: 1000 }))) },strict);
export const NetWorthValuation = Type.Object({ id: Id,itemId: Id,valueMinor: Minor,valuationDate: RecurrenceDate,note: Nullable(Type.String()),createdAt: Instant },strict);
export const NetWorthItem = Type.Object({ id: Id,...metadata,kind: NetWorthKind,currency: Currency,status: NetWorthStatus,createdAt: Instant,updatedAt: Instant,archivedAt: Nullable(Instant),latestValuation: Nullable(NetWorthValuation) },strict);
const cursor = { limit: Type.Optional(Type.String({pattern:'^([1-9]|[1-9][0-9]|100)$'})),cursorAt: Type.Optional(Instant),cursorId: Type.Optional(Id) };
const pageCursor = Type.Union([Type.Object({createdAt:Instant,id:Id},strict),Type.Null()]);
export const NetWorthItemQuery = Type.Object({...cursor,kind:Type.Optional(NetWorthKind),status:Type.Optional(NetWorthStatus),currency:Type.Optional(Currency),category:Type.Optional(NetWorthCategory)},strict);
export const NetWorthItemsPage = Type.Object({items:Type.Array(NetWorthItem),nextCursor:pageCursor},strict);
export const NetWorthValuationQuery = Type.Object({...cursor,cursorDate:Type.Optional(RecurrenceDate)},strict);
export const NetWorthValuationsPage = Type.Object({items:Type.Array(NetWorthValuation),nextCursor:Type.Union([Type.Object({valuationDate:RecurrenceDate,createdAt:Instant,id:Id},strict),Type.Null()])},strict);
export const NetWorthParams = Type.Object({itemId:Id},strict);
export const NetWorthQuery = Type.Object({asOf:Type.Optional(RecurrenceDate)},strict);
export const NetWorthHistoryQuery = Type.Object({currency:Currency,from:Type.String({pattern:'^[1-9][0-9]{3}-(0[1-9]|1[0-2])$'}),to:Type.String({pattern:'^[1-9][0-9]{3}-(0[1-9]|1[0-2])$'})},strict);
export const NetWorthTotal = Type.Object({currency:Currency,accountAssetsMinor:Aggregate,accountLiabilitiesMinor:Aggregate,accountNetMinor:Signed,manualAssetsMinor:Aggregate,manualLiabilitiesMinor:Aggregate,totalAssetsMinor:Aggregate,totalLiabilitiesMinor:Aggregate,netWorthMinor:Signed},strict);
export const NetWorthComponent = Type.Object({source:Type.Union([Type.Literal('ACCOUNT'),Type.Literal('MANUAL')]),id:Id,name:Type.String(),currency:Currency,kind:NetWorthKind,valueMinor:Aggregate,signedValueMinor:Signed,category:Nullable(NetWorthCategory),isActive:Type.Boolean(),valuationDate:Nullable(RecurrenceDate)},strict);
export const NetWorthSummary = Type.Object({asOf:RecurrenceDate,timezone:Type.String(),totals:Type.Array(NetWorthTotal),components:Type.Array(NetWorthComponent)},strict);
export const NetWorthHistory = Type.Object({currency:Currency,from:Type.String(),to:Type.String(),timezone:Type.String(),points:Type.Array(Type.Object({asOf:RecurrenceDate,...NetWorthTotal.properties},strict))},strict);
export type NetWorthItemInput = Static<typeof NetWorthItemInput>;
export type NetWorthItemPatch = Static<typeof NetWorthItemPatch>;
export type NetWorthValuationInput = Static<typeof NetWorthValuationInput>;
export type NetWorthValuation = Static<typeof NetWorthValuation>;
export type NetWorthItem = Static<typeof NetWorthItem>;
export type NetWorthItemQuery = Static<typeof NetWorthItemQuery>;
export type NetWorthValuationQuery = Static<typeof NetWorthValuationQuery>;
export type NetWorthComponent = Static<typeof NetWorthComponent>;
export type NetWorthTotal = Static<typeof NetWorthTotal>;
export type NetWorthSummary = Static<typeof NetWorthSummary>;
export type NetWorthHistory = Static<typeof NetWorthHistory>;
export type NetWorthHistoryQuery = Static<typeof NetWorthHistoryQuery>;
export type NetWorthItemsPage = Static<typeof NetWorthItemsPage>;
export type NetWorthValuationsPage = Static<typeof NetWorthValuationsPage>;
