-- Generated by drizzle-kit; named0008 to retain the repository's1-based convention.
CREATE TABLE "app"."financial_market_rates" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"benchmark" varchar(12) NOT NULL,
	"series_code" varchar(4) NOT NULL,
	"rate_date" date NOT NULL,
	"rate_value" numeric(38, 18) NOT NULL,
	"rate_unit" varchar(16) NOT NULL,
	"source" varchar(3) DEFAULT 'BCB' NOT NULL,
	"fetched_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "market_rate_observation_unique" UNIQUE("benchmark","series_code","rate_date"),
	CONSTRAINT "market_rate_value_check" CHECK ("app"."financial_market_rates"."rate_value" between 0 and 10 and "app"."financial_market_rates"."source"='BCB'),
	CONSTRAINT "market_rate_series_check" CHECK (("app"."financial_market_rates"."benchmark"='CDI' and (("app"."financial_market_rates"."series_code"='12' and "app"."financial_market_rates"."rate_unit"='DAILY_DECIMAL') or ("app"."financial_market_rates"."series_code"='4389' and "app"."financial_market_rates"."rate_unit"='ANNUAL_DECIMAL'))) or ("app"."financial_market_rates"."benchmark"='SELIC' and (("app"."financial_market_rates"."series_code"='11' and "app"."financial_market_rates"."rate_unit"='DAILY_DECIMAL') or ("app"."financial_market_rates"."series_code"='1178' and "app"."financial_market_rates"."rate_unit"='ANNUAL_DECIMAL'))) or ("app"."financial_market_rates"."benchmark"='SELIC_TARGET' and "app"."financial_market_rates"."series_code"='432' and "app"."financial_market_rates"."rate_unit"='ANNUAL_DECIMAL') or ("app"."financial_market_rates"."benchmark"='TR' and "app"."financial_market_rates"."series_code"='226' and "app"."financial_market_rates"."rate_unit"='MONTHLY_DECIMAL'))
);
--> statement-breakpoint
ALTER TABLE "app"."financial_market_rates" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."financial_yield_profiles" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"auth_user_id" uuid NOT NULL,
	"account_id" uuid NOT NULL,
	"currency" varchar(3) NOT NULL,
	"status" varchar(8) DEFAULT 'ACTIVE' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "yield_profile_account_unique" UNIQUE("account_id"),
	CONSTRAINT "yield_profile_id_owner_unique" UNIQUE("id","auth_user_id"),
	CONSTRAINT "yield_profile_status_check" CHECK ("app"."financial_yield_profiles"."status" in ('ACTIVE','ARCHIVED'))
);
--> statement-breakpoint
ALTER TABLE "app"."financial_yield_profiles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."financial_yield_rules" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"auth_user_id" uuid NOT NULL,
	"profile_id" uuid NOT NULL,
	"rule_type" varchar(20) NOT NULL,
	"effective_from" date NOT NULL,
	"effective_to" date,
	"benchmark" varchar(5),
	"fixed_rate" numeric(38, 18),
	"benchmark_percentage" numeric(38, 18),
	"rate_period" varchar(7),
	"day_count_convention" varchar(20) NOT NULL,
	"eligibility_delay_days" integer DEFAULT 0 NOT NULL,
	"eligible_balance_cap_minor" bigint,
	"tax_treatment" varchar(24) NOT NULL,
	"tax_reference_date" date,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "yield_rule_start_unique" UNIQUE("profile_id","effective_from"),
	CONSTRAINT "yield_rule_interval_check" CHECK ("app"."financial_yield_rules"."effective_from" between date '1000-01-01' and date '9988-12-31' and ("app"."financial_yield_rules"."effective_to" is null or "app"."financial_yield_rules"."effective_to">"app"."financial_yield_rules"."effective_from")),
	CONSTRAINT "yield_rule_delay_cap_check" CHECK ("app"."financial_yield_rules"."eligibility_delay_days" between 0 and 3650 and ("app"."financial_yield_rules"."eligible_balance_cap_minor" is null or "app"."financial_yield_rules"."eligible_balance_cap_minor">0)),
	CONSTRAINT "yield_rule_tax_check" CHECK ("app"."financial_yield_rules"."tax_treatment" in ('NONE','BR_FIXED_INCOME_STANDARD','BR_SAVINGS_EXEMPT') and ("app"."financial_yield_rules"."tax_reference_date" is null or "app"."financial_yield_rules"."tax_reference_date"<="app"."financial_yield_rules"."effective_from")),
	CONSTRAINT "yield_rule_shape_check" CHECK (("app"."financial_yield_rules"."rule_type"='ZERO' and "app"."financial_yield_rules"."fixed_rate" is null and "app"."financial_yield_rules"."benchmark" is null and "app"."financial_yield_rules"."benchmark_percentage" is null and "app"."financial_yield_rules"."rate_period" is null and "app"."financial_yield_rules"."day_count_convention"='CALENDAR_365' and "app"."financial_yield_rules"."tax_treatment"='NONE') or ("app"."financial_yield_rules"."rule_type"='FIXED_RATE' and "app"."financial_yield_rules"."fixed_rate" between 0 and 10 and "app"."financial_yield_rules"."benchmark" is null and "app"."financial_yield_rules"."benchmark_percentage" is null and "app"."financial_yield_rules"."rate_period" in ('ANNUAL','MONTHLY') and "app"."financial_yield_rules"."day_count_convention" in ('CALENDAR_365','BUSINESS_252') and "app"."financial_yield_rules"."tax_treatment" in ('NONE','BR_FIXED_INCOME_STANDARD')) or ("app"."financial_yield_rules"."rule_type"='BENCHMARK_PERCENTAGE' and "app"."financial_yield_rules"."fixed_rate" is null and "app"."financial_yield_rules"."benchmark" in ('CDI','SELIC') and "app"."financial_yield_rules"."benchmark_percentage" between 0 and 10 and "app"."financial_yield_rules"."rate_period" is null and "app"."financial_yield_rules"."day_count_convention"='BUSINESS_252' and "app"."financial_yield_rules"."tax_treatment" in ('NONE','BR_FIXED_INCOME_STANDARD')) or ("app"."financial_yield_rules"."rule_type"='SAVINGS_BR' and "app"."financial_yield_rules"."fixed_rate" is null and "app"."financial_yield_rules"."benchmark" is null and "app"."financial_yield_rules"."benchmark_percentage" is null and "app"."financial_yield_rules"."rate_period" is null and "app"."financial_yield_rules"."day_count_convention"='MONTHLY_ANNIVERSARY' and "app"."financial_yield_rules"."tax_treatment"='BR_SAVINGS_EXEMPT'))
);
--> statement-breakpoint
ALTER TABLE "app"."financial_yield_rules" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "app"."financial_yield_profiles" ADD CONSTRAINT "yield_profile_account_owner_currency_fk" FOREIGN KEY ("account_id","auth_user_id","currency") REFERENCES "app"."financial_accounts"("id","auth_user_id","currency") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."financial_yield_rules" ADD CONSTRAINT "yield_rule_profile_owner_fk" FOREIGN KEY ("profile_id","auth_user_id") REFERENCES "app"."financial_yield_profiles"("id","auth_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "market_rate_series_date_idx" ON "app"."financial_market_rates" USING btree ("series_code","rate_date");--> statement-breakpoint
CREATE INDEX "yield_profile_owner_idx" ON "app"."financial_yield_profiles" USING btree ("auth_user_id");--> statement-breakpoint
CREATE INDEX "yield_rule_owner_profile_date_idx" ON "app"."financial_yield_rules" USING btree ("auth_user_id","profile_id","effective_from");--> statement-breakpoint
CREATE POLICY "yield_profile_select_own" ON "app"."financial_yield_profiles" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid())="app"."financial_yield_profiles"."auth_user_id");--> statement-breakpoint
CREATE POLICY "yield_profile_insert_own" ON "app"."financial_yield_profiles" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select auth.uid())="app"."financial_yield_profiles"."auth_user_id");--> statement-breakpoint
CREATE POLICY "yield_profile_update_own" ON "app"."financial_yield_profiles" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select auth.uid())="app"."financial_yield_profiles"."auth_user_id") WITH CHECK ((select auth.uid())="app"."financial_yield_profiles"."auth_user_id");--> statement-breakpoint
CREATE POLICY "yield_rule_select_own" ON "app"."financial_yield_rules" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid())="app"."financial_yield_rules"."auth_user_id");--> statement-breakpoint
CREATE POLICY "yield_rule_insert_own" ON "app"."financial_yield_rules" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select auth.uid())="app"."financial_yield_rules"."auth_user_id" and exists(select 1 from app.financial_yield_profiles p where p.id="app"."financial_yield_rules"."profile_id" and p.auth_user_id="app"."financial_yield_rules"."auth_user_id" and p.status='ACTIVE'));
--> statement-breakpoint
-- Reviewed incremental integrity supplement. Invoker only; no privilege escalation
-- or grants. Parent row lock serializes interval checks, including direct inserts.
CREATE FUNCTION app.validate_yield_rule() RETURNS trigger
LANGUAGE plpgsql SECURITY INVOKER SET search_path = '' AS $body$
DECLARE profile_currency text; profile_status text;
BEGIN
  SELECT currency,status INTO profile_currency,profile_status
    FROM app.financial_yield_profiles WHERE id=NEW.profile_id AND auth_user_id=NEW.auth_user_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Yield profile ownership mismatch' USING ERRCODE='23503'; END IF;
  IF profile_status <> 'ACTIVE' THEN RAISE EXCEPTION 'Yield profile archived' USING ERRCODE='23514'; END IF;
  IF TG_OP='UPDATE' AND (OLD.effective_to IS NOT NULL OR NEW.effective_to IS NULL OR NEW.effective_to<=OLD.effective_from OR
    (to_jsonb(NEW)-'effective_to') IS DISTINCT FROM (to_jsonb(OLD)-'effective_to')) THEN
    RAISE EXCEPTION 'Yield rules are immutable except first interval closure' USING ERRCODE='23514';
  END IF;
  IF (NEW.rule_type='FIXED_RATE' AND (NEW.fixed_rate IS NULL OR NEW.rate_period IS NULL)) OR
     (NEW.rule_type='BENCHMARK_PERCENTAGE' AND (NEW.benchmark IS NULL OR NEW.benchmark_percentage IS NULL)) THEN
    RAISE EXCEPTION 'Yield rule missing required rate' USING ERRCODE='23514';
  END IF;
  IF profile_currency<>'BRL' AND (NEW.rule_type IN ('BENCHMARK_PERCENTAGE','SAVINGS_BR') OR NEW.tax_treatment<>'NONE') THEN
    RAISE EXCEPTION 'Brazilian yield rules require BRL' USING ERRCODE='23514';
  END IF;
  IF EXISTS(SELECT 1 FROM app.financial_yield_rules r WHERE r.profile_id=NEW.profile_id AND r.id<>NEW.id
    AND daterange(r.effective_from,r.effective_to,'[)') && daterange(NEW.effective_from,NEW.effective_to,'[)')) THEN
    RAISE EXCEPTION 'Yield rule intervals overlap' USING ERRCODE='23514';
  END IF;
  RETURN NEW;
END $body$;
--> statement-breakpoint
REVOKE ALL ON FUNCTION app.validate_yield_rule() FROM PUBLIC,anon,authenticated;
--> statement-breakpoint
CREATE TRIGGER yield_rule_integrity BEFORE INSERT OR UPDATE ON app.financial_yield_rules FOR EACH ROW EXECUTE FUNCTION app.validate_yield_rule();
--> statement-breakpoint
CREATE FUNCTION app.validate_yield_profile() RETURNS trigger
LANGUAGE plpgsql SECURITY INVOKER SET search_path = '' AS $body$
BEGIN
  IF NEW.id<>OLD.id OR NEW.auth_user_id<>OLD.auth_user_id OR NEW.account_id<>OLD.account_id OR NEW.currency<>OLD.currency OR NEW.created_at<>OLD.created_at OR (OLD.status='ARCHIVED' AND NEW.status<>'ARCHIVED') THEN
    RAISE EXCEPTION 'Yield profile identity and archive are immutable' USING ERRCODE='23514';
  END IF;
  RETURN NEW;
END $body$;
--> statement-breakpoint
REVOKE ALL ON FUNCTION app.validate_yield_profile() FROM PUBLIC,anon,authenticated;
--> statement-breakpoint
CREATE TRIGGER yield_profile_integrity BEFORE UPDATE ON app.financial_yield_profiles FOR EACH ROW EXECUTE FUNCTION app.validate_yield_profile();
