import { randomUUID } from 'node:crypto';
import { beforeAll, afterAll, describe, it, expect } from 'vitest';
import type { PoolClient } from 'pg';
import { createDatabase } from '../../src/db/client.js';
import { loadConfig } from '../../src/config/env.js';
import { buildApp } from '../../src/app.js';
import { createProfileRepository } from '../../src/modules/profile/repository.js';
import { createFinanceRepository } from '../../src/modules/finance/repository.js';
import { createBudgetRepository } from '../../src/modules/finance/budget-repository.js';
import { createGoalRepository } from '../../src/modules/finance/goal-repository.js';
import { signingFixture, testEnv } from '../helpers.js';
import type { Goal, GoalEvent, GoalEventsPage } from '../../src/modules/finance/goal-contracts.js';
const database = createDatabase(loadConfig({ ...testEnv, TEST_DATABASE_URL: process.env.TEST_DATABASE_URL }));
const fixture = await signingFixture();
const app = await buildApp(loadConfig({ ...testEnv, RATE_LIMIT_MAX: '5000', TEST_DATABASE_URL: process.env.TEST_DATABASE_URL }), { jwks: fixture.resolver, goalClock: () => new Date('2026-10-15T12:00:00Z'), dependencies: { profiles: createProfileRepository(database), finance: createFinanceRepository(database), budgets: createBudgetRepository(database), goals: createGoalRepository(database), ping: database.ping, close: database.close } });
const base = '/api/v1/finance/goals';
const input = { name: 'Reserva', currency: 'BRL', targetAmountMinor: '1000000', targetMonth: '2026-12', plannedMonthlyMinor: '100000', priority: 'HIGH' };
type Context = { owner: string; headers: { authorization: string } };
async function context(): Promise<Context> { const owner = randomUUID(); return { owner, headers: { authorization: `Bearer ${await fixture.token({ sub: owner })}` } }; }
async function request<T>(c: Context, method: 'GET' | 'POST' | 'PATCH', suffix = '', payload?: Record<string, unknown>, status = method === 'POST' ? 201 : 200): Promise<T> { const r = await app.inject({ method, url: base + suffix, headers: c.headers, ...(payload ? { payload } : {}) }); expect(r.statusCode, r.body).toBe(status); return r.json<T>(); }
const create = (c: Context, override = {}) => request<Goal>(c, 'POST', '', { ...input, ...override });
const add = (c: Context, id: string, type = 'CONTRIBUTION', amountMinor = '250000', override = {}, status = 201) => request<GoalEvent>(c, 'POST', `/${id}/events`, { type, amountMinor, occurredAt: '2026-10-10T12:00:00Z', idempotencyKey: randomUUID(), ...override }, status);
beforeAll(async () => { await database.ping(); });
afterAll(async () => { await app.close(); });
describe('financial goals PostgreSQL API and invariants', () => {
  it('creates, lists by owner/status/currency/priority and preserves reload reads', async () => { const a = await context(), b = await context(); const goal = await create(a); const usd = await create(a, { currency: 'USD', priority: 'LOW' }); await create(b); expect(goal).toMatchObject({ currentAmountMinor: '0', remainingAmountMinor: '1000000', progressPercent: '0.00', requiredMonthlyMinor: '333334', status: 'ACTIVE' }); expect(await request<Goal[]>(a, 'GET', '?currency=BRL&status=ACTIVE')).toEqual([goal]); expect((await request<Goal[]>(a, 'GET')).map(g => g.id)).toEqual([goal.id, usd.id]); expect(await request<Goal>(a, 'GET', '/' + goal.id)).toEqual(goal); });
  it('adds immutable contributions/withdrawals and recalculates after editing target', async () => { const a = await context(), goal = await create(a); await add(a, goal.id); expect(await request<Goal>(a, 'GET', '/' + goal.id)).toMatchObject({ currentAmountMinor: '250000', progressPercent: '25.00' }); await add(a, goal.id, 'WITHDRAWAL', '50000'); const changed = await request<Goal>(a, 'PATCH', '/' + goal.id, { targetAmountMinor: '1200000', description: 'Planejamento' }); expect(changed).toMatchObject({ currentAmountMinor: '200000', remainingAmountMinor: '1000000', progressPercent: '16.66' }); const history = await request<GoalEventsPage>(a, 'GET', `/${goal.id}/events`); expect(history.items).toHaveLength(2); expect(new Set(history.items.map(e => e.type))).toEqual(new Set(['CONTRIBUTION', 'WITHDRAWAL'])); });
  it('replays concurrently with one persisted event and conflicts on any changed content', async () => { const a = await context(), goal = await create(a), idempotencyKey = randomUUID(); const [first, replay] = await Promise.all([add(a, goal.id, 'CONTRIBUTION', '100', { idempotencyKey }), add(a, goal.id, 'CONTRIBUTION', '100', { idempotencyKey })]); expect(replay.id).toBe(first.id); expect((await request<GoalEventsPage>(a, 'GET', `/${goal.id}/events`)).items).toHaveLength(1); for (const override of [{ amountMinor: '101' }, { type: 'WITHDRAWAL' }, { note: 'changed' }, { occurredAt: '2026-10-11T12:00:00Z' }]) await add(a, goal.id, 'CONTRIBUTION', '100', { idempotencyKey, ...override }, 409); const other = await create(a); await add(a, other.id, 'CONTRIBUTION', '100', { idempotencyKey }, 409); });
  it('uses owner-scoped keys and canonical replay content', async () => { const a = await context(), b = await context(), x = await create(a), y = await create(b), idempotencyKey = randomUUID(); const first = await add(a, x.id, 'CONTRIBUTION', '100', { idempotencyKey, note: ' Nota ' }); expect((await add(a, x.id.toUpperCase(), 'CONTRIBUTION', '100', { idempotencyKey: idempotencyKey.toUpperCase(), note: 'Nota', occurredAt: '2026-10-10T09:00:00-03:00' })).id).toBe(first.id); await add(b, y.id, 'CONTRIBUTION', '100', { idempotencyKey }); });
  it('rejects overdraft and serializes simultaneous withdrawals', async () => { const a = await context(), g = await create(a); await add(a, g.id, 'WITHDRAWAL', '1', {}, 409); await add(a, g.id, 'CONTRIBUTION', '100'); const results = await Promise.all([1, 2].map(() => app.inject({ method: 'POST', url: `${base}/${g.id}/events`, headers: a.headers, payload: { type: 'WITHDRAWAL', amountMinor: '80', occurredAt: '2026-10-10T12:00:00Z', idempotencyKey: randomUUID() } }))); expect(results.map(r => r.statusCode).sort()).toEqual([201, 409]); expect(await request<Goal>(a, 'GET', '/' + g.id)).toMatchObject({ currentAmountMinor: '20' }); });
  it('pauses/resumes/archives while preserving progress/history and safe replay', async () => { const a = await context(), g = await create(a), key = randomUUID(); const e = await add(a, g.id, 'CONTRIBUTION', '100', { idempotencyKey: key }); await request(a, 'PATCH', '/' + g.id, { status: 'PAUSED' }); await add(a, g.id, 'CONTRIBUTION', '1', {}, 409); await add(a, g.id, 'WITHDRAWAL', '1', {}, 409); await request(a, 'PATCH', '/' + g.id, { status: 'ACTIVE' }); await add(a, g.id, 'CONTRIBUTION', '1'); const archived = await request<Goal>(a, 'PATCH', '/' + g.id, { status: 'ARCHIVED' }); expect(archived.archivedAt).not.toBeNull(); expect((await request<Goal[]>(a, 'GET', '?status=ARCHIVED'))[0]!.currentAmountMinor).toBe('101'); expect((await add(a, g.id, 'CONTRIBUTION', '100', { idempotencyKey: key })).id).toBe(e.id); await add(a, g.id, 'CONTRIBUTION', '1', {}, 409); await request(a, 'PATCH', '/' + g.id, { status: 'ACTIVE' }, 409); });
  it('protects foreign IDs consistently with 404 for every goal/event operation', async () => { const a = await context(), b = await context(), g = await create(a); await request(b, 'GET', '/' + g.id, undefined, 404); await request(b, 'PATCH', '/' + g.id, { name: 'Foreign' }, 404); await request(b, 'GET', `/${g.id}/events`, undefined, 404); await add(b, g.id, 'CONTRIBUTION', '100', {}, 404); });
  it.each([{ auth_user_id: randomUUID() }, { currentAmountMinor: '1' }, { progress: '100' }, { requiredMonthlyMinor: '1' }, { estimatedCompletionMonth: '2026-12' }, { targetAmountMinor: '0' }, { targetAmountMinor: '-1' }, { targetAmountMinor: '9223372036854775808' }, { plannedMonthlyMinor: '-1' }, { targetMonth: '2026-13' }, { targetMonth: '9999-01' }, { priority: 'URGENT' }, { currency: 'XXX' }, { name: ' ' }])('rejects invalid/untrusted create input %j', async override => { const a = await context(); await request(a, 'POST', '', { ...input, ...override }, 400); });
  it('rejects readonly patch fields, empty patches and event currency/zero amounts', async () => { const a = await context(), g = await create(a); for (const patch of [{}, { currency: 'USD' }, { currentAmountMinor: '1' }, { authUserId: a.owner }]) await request(a, 'PATCH', '/' + g.id, patch, 400); await add(a, g.id, 'CONTRIBUTION', '0', {}, 400); await add(a, g.id, 'CONTRIBUTION', '1', { currency: 'USD' }, 400); await request(a, 'GET', `/${g.id}/events?cursorId=${randomUUID()}`, undefined, 400); });
  it('paginates tied event timestamps without duplication', async () => { const a = await context(), g = await create(a); for (let i = 0; i < 3; i++) await add(a, g.id, 'CONTRIBUTION', '1'); const first = await request<GoalEventsPage>(a, 'GET', `/${g.id}/events?limit=2`); const cursor = first.nextCursor!; const second = await request<GoalEventsPage>(a, 'GET', `/${g.id}/events?limit=2&cursorAt=${encodeURIComponent(cursor.occurredAt)}&cursorId=${cursor.id}`); expect(new Set([...first.items, ...second.items].map(e => e.id)).size).toBe(3); expect(second.nextCursor).toBeNull(); });
  it('never changes accounts, transactions, transfers or budgets', async () => { const a = await context(); const counts = async () => { const r = await database.pool.query("select (select count(*) from app.financial_accounts) as accounts, (select count(*) from app.financial_transactions) as transactions, (select count(*) from app.financial_transfers) as transfers, (select count(*) from app.financial_budget_periods) as periods, (select count(*) from app.financial_budget_allocations) as allocations"); return r.rows[0]; }; const before = await counts(); const g = await create(a); await add(a, g.id); await add(a, g.id, 'WITHDRAWAL', '50000'); await request(a, 'PATCH', '/' + g.id, { status: 'ARCHIVED' }); expect(await counts()).toEqual(before); });
  it('enforces RLS and append-only events and rejects cross-owner FKs', async () => { const a = await context(), b = await context(), g = await create(a), e = await add(a, g.id); async function asRole<T>(role: 'authenticated' | 'anon', owner: string, action: (c: PoolClient) => Promise<T>) { const c = await database.pool.connect(); try { await c.query('begin'); await c.query(`set local role ${role}`); await c.query("select set_config('request.jwt.claim.sub',$1,true)", [owner]); return await action(c); } finally { await c.query('rollback'); c.release(); } }
    for (const [table, id] of [['financial_goals', g.id], ['financial_goal_events', e.id]]) { const select = `select id from app.${table} where id=$1`; expect((await asRole('authenticated', a.owner, c => c.query(select, [id]))).rowCount).toBe(1); expect((await asRole('authenticated', b.owner, c => c.query(select, [id]))).rowCount).toBe(0); expect((await asRole('anon', '', c => c.query(select, [id]))).rowCount).toBe(0); expect((await asRole('authenticated', a.owner, c => c.query(`delete from app.${table} where id=$1`, [id]))).rowCount).toBe(0); }
    expect((await asRole('authenticated', a.owner, c => c.query('update app.financial_goal_events set note=$1 where id=$2', ['silent rewrite', e.id]))).rowCount).toBe(0);
    await expect(asRole('authenticated', a.owner, c => c.query('update app.financial_goals set auth_user_id=$1 where id=$2', [b.owner, g.id]))).rejects.toMatchObject({ code: '42501' });
    await expect(asRole('authenticated', b.owner, c => c.query('insert into app.financial_goals(auth_user_id,name,currency,target_amount_minor,priority) values($1,$2,$3,$4,$5)', [a.owner, 'Foreign', 'BRL', '100', 'HIGH']))).rejects.toMatchObject({ code: '42501' });
    const insert = 'insert into app.financial_goal_events(auth_user_id,goal_id,type,amount_minor,occurred_at,idempotency_key) values($1,$2,$3,$4,now(),$5)';
    await expect(asRole('authenticated', a.owner, c => c.query(insert, [a.owner, g.id, 'CONTRIBUTION', '100', randomUUID()]))).rejects.toMatchObject({ code: '42501' });
    await expect(database.pool.query(insert, [b.owner, g.id, 'CONTRIBUTION', '100', randomUUID()])).rejects.toMatchObject({ code: '23503' });
    await expect(database.pool.query(insert, [a.owner, g.id, 'CONTRIBUTION', '0', randomUUID()])).rejects.toMatchObject({ code: '23514' });
  });
});
