import { randomUUID } from 'node:crypto';
import { afterAll,describe,it,expect } from 'vitest';
import { createDatabase } from '../../src/db/client.js';
import { loadConfig } from '../../src/config/env.js';
import { buildApp } from '../../src/app.js';
import { createProfileRepository } from '../../src/modules/profile/repository.js';
import { createFinanceRepository } from '../../src/modules/finance/repository.js';
import { createNetWorthRepository } from '../../src/modules/finance/net-worth-repository.js';
import { signingFixture,testEnv } from '../helpers.js';
import type { NetWorthItem,NetWorthSummary,NetWorthHistory,NetWorthValuationsPage } from '../../src/modules/finance/net-worth-contracts.js';
const config=loadConfig({...testEnv,RATE_LIMIT_MAX:'10000',TEST_DATABASE_URL:process.env.TEST_DATABASE_URL}),database=createDatabase(config),profiles=createProfileRepository(database),netWorth=createNetWorthRepository(database),finance=createFinanceRepository(database),fixture=await signingFixture();
const app=await buildApp(config,{jwks:fixture.resolver,netWorthClock:()=>new Date('2026-10-06T01:00:00Z'),dependencies:{profiles,finance,netWorth,ping:database.ping,close:database.close}});
type Context={owner:string;headers:{authorization:string}};
async function context(zone?:string):Promise<Context>{const owner=randomUUID();if(zone)await profiles.upsertForAuthUser(owner,{displayName:'Test',locale:'pt-BR',timezone:zone});return{owner,headers:{authorization:'Bearer '+await fixture.token({sub:owner})}};}
async function req<T>(c:Context,path:string,method:'GET'|'POST'|'PATCH'='GET',payload?:unknown,status=method==='POST'?201:200):Promise<T>{const r=await app.inject({method,url:'/api/v1/finance/net-worth'+path,headers:c.headers,...(payload?{payload:payload as Record<string,unknown>}:{})});expect(r.statusCode,r.body).toBe(status);return r.json<T>();}
const input={name:'Carro',kind:'ASSET',category:'VEHICLE',currency:'BRL',initialValueMinor:'10000',valuationDate:'2026-01-01'};
const create=(c:Context,extra={},status=201)=>req<NetWorthItem>(c,'/items','POST',{...input,...extra},status);
afterAll(()=>app.close());
describe('net worth PostgreSQL17 API and RLS',()=>{
 it('RLS enforces owned inserts, append-only valuations and archived item rejection',async()=>{
  const a=await context(),b=await context(),item=await create(a),client=await database.pool.connect();
  const start=async(owner:string)=>{await client.query('begin');await client.query('set local role authenticated');await client.query("select set_config('request.jwt.claim.sub',$1,true)",[owner]);};
  try{
   await start(a.owner);await client.query("insert into app.financial_net_worth_valuations(auth_user_id,item_id,value_minor,valuation_date) values($1,$2,0,'2026-10-01')",[a.owner,item.id]);expect((await client.query('update app.financial_net_worth_valuations set value_minor=1 where item_id=$1 returning id',[item.id])).rowCount).toBe(0);expect((await client.query('delete from app.financial_net_worth_valuations where item_id=$1 returning id',[item.id])).rowCount).toBe(0);await client.query('rollback');
   await start(b.owner);await expect(client.query("insert into app.financial_net_worth_valuations(auth_user_id,item_id,value_minor,valuation_date) values($1,$2,1,'2026-10-01')",[b.owner,item.id])).rejects.toMatchObject({code:'42501'});await client.query('rollback');
   await start(a.owner);await expect(client.query("insert into app.financial_net_worth_items(auth_user_id,name,kind,category,currency) values($1,'Spoof','ASSET','VEHICLE','BRL')",[b.owner])).rejects.toMatchObject({code:'42501'});await client.query('rollback');
   await req(a,'/items/'+item.id+'/archive','POST',{},200);await start(a.owner);await expect(client.query("insert into app.financial_net_worth_valuations(auth_user_id,item_id,value_minor,valuation_date) values($1,$2,1,'2026-10-01')",[a.owner,item.id])).rejects.toMatchObject({code:'42501'});
  }finally{await client.query('rollback');client.release();}
 });
 it('archive cutoff excludes current position, retains nonzero history and is idempotent',async()=>{const c=await context(),item=await create(c);await req(c,'/items/'+item.id+'/archive','POST',{},200);const archived=await req<NetWorthItem>(c,'/items/'+item.id);await req(c,'/items/'+item.id+'/archive','POST',{},200);expect((await req<NetWorthItem>(c,'/items/'+item.id)).archivedAt).toBe(archived.archivedAt);await req(c,'/items/'+item.id,'PATCH',{name:'No edit'},409);expect((await req<NetWorthSummary>(c,'?asOf=2026-09-30')).totals[0]?.netWorthMinor).toBe('10000');expect((await req<NetWorthSummary>(c,'')).components).toHaveLength(0);expect((await req<NetWorthValuationsPage>(c,'/items/'+item.id+'/valuations')).items).toHaveLength(1);});
 it('atomic create, metadata, zero valuation, history preservation and terminal archive',async()=>{const c=await context(),item=await create(c);expect(item.latestValuation?.valueMinor).toBe('10000');await req(c,'/items/'+item.id,'PATCH',{name:'Carro novo'});await req(c,'/items/'+item.id+'/valuations','POST',{valueMinor:'8000',valuationDate:'2026-03-01'});let hist=await req<NetWorthHistory>(c,'/history?currency=BRL&from=2026-01&to=2026-03');expect(hist.points.map(p=>p.netWorthMinor)).toEqual(['10000','10000','8000']);await req(c,'/items/'+item.id+'/valuations','POST',{valueMinor:'0',valuationDate:'2026-10-01'});expect((await req<NetWorthValuationsPage>(c,'/items/'+item.id+'/valuations')).items).toHaveLength(3);await req(c,'/items/'+item.id+'/archive','POST',{},200);await req(c,'/items/'+item.id+'/valuations','POST',{valueMinor:'1',valuationDate:'2026-10-01'},409);hist=await req(c,'/history?currency=BRL&from=2026-01&to=2026-03');expect(hist.points[2]?.netWorthMinor).toBe('8000');expect((await req<NetWorthSummary>(c,'')).components).toHaveLength(0);});
 it('same-date tie is deterministic by timestamp and UUID, not sum',async()=>{const c=await context(),item=await create(c);await database.pool.query('update app.financial_net_worth_valuations set created_at=$1 where item_id=$2',['2026-01-01T00:00:00Z',item.id]);await database.pool.query("insert into app.financial_net_worth_valuations(id,auth_user_id,item_id,value_minor,valuation_date,created_at) values($1,$2,$3,200,'2026-01-01','2026-01-01'),($4,$2,$3,300,'2026-01-01','2026-01-01')",['aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',c.owner,item.id,'ffffffff-ffff-4fff-8fff-ffffffffffff']);expect((await req<NetWorthSummary>(c,'?asOf=2026-01-01')).totals[0]?.netWorthMinor).toBe('300');});
 it('signed active/inactive accounts, transfers, cancelled/future transactions and local cutoff',async()=>{const c=await context('America/Sao_Paulo');const a=await finance.createAccount(c.owner,{name:'Positive',type:'checking',currency:'BRL',initialBalanceMinor:'10000'}),b=await finance.createAccount(c.owner,{name:'Negative',type:'credit',currency:'BRL',initialBalanceMinor:'-2000'});await database.pool.query("update app.financial_accounts set created_at='2026-01-01T03:00:00Z',is_active=false where id=any($1::uuid[])",[[a.id,b.id]]);const insert=async(type:string,amount:string,at:string,cancelled=false)=>database.pool.query('insert into app.financial_transactions(auth_user_id,account_id,type,amount_minor,currency,description,occurred_at,is_cancelled) values($1,$2,$3,$4,\'BRL\',\'Fixture\',$5,$6)',[c.owner,a.id,type,amount,at,cancelled]);await insert('INCOME','500','2026-10-06T02:59:59Z');await insert('INCOME','999','2026-10-06T03:00:00Z');await insert('EXPENSE','999','2026-10-01',true);await database.pool.query("insert into app.financial_transfers(auth_user_id,source_account_id,destination_account_id,amount_minor,currency,description,occurred_at,idempotency_key) values($1,$2,$3,1000,'BRL','Fixture','2026-10-05',$4)",[c.owner,a.id,b.id,randomUUID()]);const result=await req<NetWorthSummary>(c,'');expect(result.asOf).toBe('2026-10-05');expect(result.timezone).toBe('America/Sao_Paulo');expect(result.totals[0]).toMatchObject({accountAssetsMinor:'9500',accountLiabilitiesMinor:'1000',accountNetMinor:'8500'});expect((await req<NetWorthSummary>(c,'?asOf=2025-12-31')).components).toHaveLength(0);});
 it('manual assets/liabilities, multi-currency, account-only and exact huge totals',async()=>{const c=await context();await create(c,{initialValueMinor:'9223372036854775807'});await create(c,{initialValueMinor:'9223372036854775807'});await create(c,{kind:'LIABILITY',category:'LOAN',initialValueMinor:'30'});await create(c,{currency:'USD',initialValueMinor:'500'});const s=await req<NetWorthSummary>(c,'');expect(s.timezone).toBe('UTC');expect(s.totals[0]?.netWorthMinor).toBe('18446744073709551584');expect(s.totals[1]?.netWorthMinor).toBe('500');});
 it('strict inputs, dates, metadata immutability, filters, pagination, max60 and rollback',async()=>{const c=await context();for(const extra of [{initialValueMinor:'0'},{initialValueMinor:'-1'},{category:'MORTGAGE'},{valuationDate:'2026-10-07'},{valuationDate:'2026-02-30'},{ownerId:randomUUID()}])await create(c,extra,400);const item=await create(c);for(const extra of [{currency:'USD'},{kind:'LIABILITY'},{currentValue:'50'},{status:'ARCHIVED'},{category:'LOAN'}])await req(c,'/items/'+item.id,'PATCH',extra,400);await req(c,'/history?currency=BRL&from=2021-01&to=2026-10','GET',undefined,400);await req(c,'/history?currency=BRL&from=2026-11&to=2026-11','GET',undefined,400);await req(c,'/items?cursorId='+item.id,'GET',undefined,400);expect((await req<{items:unknown[]}>(c,'/items?kind=LIABILITY')).items).toHaveLength(0);await create(c);const page=await req<{items:NetWorthItem[];nextCursor:{createdAt:string;id:string}}>(c,'/items?limit=1');expect(page.items).toHaveLength(1);expect((await req<{items:NetWorthItem[]}>(c,'/items?limit=1&cursorAt='+encodeURIComponent(page.nextCursor.createdAt)+'&cursorId='+page.nextCursor.id)).items[0]?.id).not.toBe(page.items[0]?.id);const before=await database.pool.query('select count(*)::text n from app.financial_net_worth_items where auth_user_id=$1',[c.owner]);await expect(netWorth.create(c.owner,{...input,kind:'ASSET',currency:'BRL',category:'VEHICLE',valuationDate:'bad-date'})).rejects.toThrow();expect((await database.pool.query('select count(*)::text n from app.financial_net_worth_items where auth_user_id=$1',[c.owner])).rows).toEqual(before.rows);});
 it('A/B ownership on all APIs, composite FK and RLS SELECT/INSERT/UPDATE/DELETE',async()=>{const a=await context(),b=await context(),item=await create(a);for(const [path,method,payload] of [[`/items/${item.id}`,'GET',undefined],[`/items/${item.id}`,'PATCH',{name:'Steal'}],[`/items/${item.id}/archive`,'POST',{}],[`/items/${item.id}/valuations`,'GET',undefined],[`/items/${item.id}/valuations`,'POST',{valueMinor:'1',valuationDate:'2026-01-01'}]] as const)await req(b,path,method,payload,404);expect((await req<NetWorthSummary>(b,'')).components).toHaveLength(0);expect((await req<NetWorthHistory>(b,'/history?currency=BRL&from=2026-01&to=2026-02')).points.every(p=>p.netWorthMinor==='0')).toBe(true);await expect(database.pool.query("insert into app.financial_net_worth_valuations(auth_user_id,item_id,value_minor,valuation_date) values($1,$2,1,'2026-01-01')",[b.owner,item.id])).rejects.toMatchObject({code:'23503'});const client=await database.pool.connect();try{await client.query('begin');await client.query('set local role authenticated');await client.query("select set_config('request.jwt.claim.sub',$1,true)",[b.owner]);expect((await client.query('select id from app.financial_net_worth_items where id=$1',[item.id])).rows).toHaveLength(0);expect((await client.query('select id from app.financial_net_worth_valuations where item_id=$1',[item.id])).rows).toHaveLength(0);expect((await client.query("update app.financial_net_worth_items set name='Steal' where id=$1 returning id",[item.id])).rows).toHaveLength(0);expect((await client.query('delete from app.financial_net_worth_items where id=$1 returning id',[item.id])).rows).toHaveLength(0);await client.query('rollback');await client.query('begin');await client.query('set local role authenticated');await client.query("select set_config('request.jwt.claim.sub',$1,true)",[a.owner]);expect((await client.query('select id from app.financial_net_worth_items where id=$1',[item.id])).rows).toHaveLength(1);await expect(client.query("update app.financial_net_worth_items set auth_user_id=$1 where id=$2",[b.owner,item.id])).rejects.toMatchObject({code:'42501'});}finally{await client.query('rollback');client.release();}});
 it('writes never touch the existing ledger/budgets/goals/recurrences',async()=>{const c=await context();await finance.createAccount(c.owner,{name:'Core',type:'checking',currency:'BRL',initialBalanceMinor:'100'});const tables=['financial_accounts','financial_transactions','financial_transfers','financial_budget_periods','financial_budget_allocations','financial_goals','financial_goal_events','financial_recurrences'];const snapshot=async()=>Promise.all(tables.map(async table=>(await database.pool.query('select md5(coalesce(jsonb_agg(to_jsonb(t) order by id)::text,\'[]\')) h from app.'+table+' t where auth_user_id=$1',[c.owner])).rows[0]?.h));const before=await snapshot();const item=await create(c);await req(c,'/items/'+item.id,'PATCH',{name:'Other'});await req(c,'/items/'+item.id+'/valuations','POST',{valueMinor:'0',valuationDate:'2026-01-01'});await req(c,'/items/'+item.id+'/archive','POST',{},200);expect(await snapshot()).toEqual(before);});
});
