import { randomUUID } from 'node:crypto';
import { afterAll,describe,it,expect,vi } from 'vitest';
import pg from 'pg';
import { sql } from 'drizzle-orm';
import { createDatabase } from '../../src/db/client.js';
import { loadConfig } from '../../src/config/env.js';
import { buildApp } from '../../src/app.js';
import { createProfileRepository } from '../../src/modules/profile/repository.js';
import { createFinanceRepository } from '../../src/modules/finance/repository.js';
import { createSafeSpendRepository } from '../../src/modules/finance/safe-spend-repository.js';
import { createCardRepository } from '../../src/modules/finance/card-repository.js';
import { createDebtRepository } from '../../src/modules/finance/debt-repository.js';
import { createGoalRepository } from '../../src/modules/finance/goal-repository.js';
import { createRecurrenceRepository } from '../../src/modules/finance/recurrence-repository.js';
import { createBudgetRepository } from '../../src/modules/finance/budget-repository.js';
import { signingFixture,testEnv } from '../helpers.js';
import type { SafeSpendSettings,SafeSpendView } from '../../src/modules/finance/safe-spend-contracts.js';
const config=loadConfig({...testEnv,RATE_LIMIT_MAX:'10000',TEST_DATABASE_URL:process.env.TEST_DATABASE_URL}),database=createDatabase(config),profiles=createProfileRepository(database),finance=createFinanceRepository(database),safeSpend=createSafeSpendRepository(database),cards=createCardRepository(database),debts=createDebtRepository(database),goals=createGoalRepository(database),recurrences=createRecurrenceRepository(database),budgets=createBudgetRepository(database),fixture=await signingFixture(),now=new Date('2026-10-22T12:00:00Z');
const app=await buildApp(config,{jwks:fixture.resolver,safeSpendClock:()=>now,dependencies:{profiles,finance,safeSpend,ping:database.ping,close:database.close}});
async function context(zone='UTC'){const owner=randomUUID();await profiles.upsertForAuthUser(owner,{displayName:'Safe fixture',locale:'pt-BR',timezone:zone});const a=await finance.createAccount(owner,{name:'Liquid bank',type:'checking',currency:'BRL',initialBalanceMinor:'500000'}),c=await finance.createCategory(owner,{name:'Expense',kind:'EXPENSE'});return {owner,account:a.id,category:c.id,headers:{authorization:'Bearer '+await fixture.token({sub:owner})}};}
type Context=Awaited<ReturnType<typeof context>>;
const input=(c:Context,extra={})=>({currency:'BRL',accountIds:[c.account],safetyBufferMinor:'50000',respectBudget:true,reserveRecurrences:true,reserveGoalPlans:true,...extra});
async function request(c:Context,path='',method:'GET'|'PUT'='GET',payload?:unknown,status=200){const r=await app.inject({method,url:'/api/v1/finance/safe-to-spend'+path,headers:c.headers,...(payload?{payload:payload as Record<string,unknown>}:{})});expect(r.statusCode,r.body).toBe(status);return r;}
const put=async(c:Context,extra={})=>(await request(c,'/settings','PUT',input(c,extra))).json<SafeSpendSettings>();
const view=async(c:Context)=>(await request(c,'?currency=BRL')).json<SafeSpendView>();
async function ownSnapshot(owner:string){const result:Record<string,unknown>={};for(const t of ['financial_accounts','financial_categories','financial_transactions','financial_transfers','financial_budget_periods','financial_budget_allocations','financial_goals','financial_goal_events','financial_recurrences','financial_net_worth_items','financial_net_worth_valuations','financial_yield_profiles','financial_yield_rules','financial_credit_cards','financial_card_billing_rules','financial_card_purchases','financial_card_installments','financial_debts','financial_debt_terms','financial_debt_payments']){const r=await database.pool.query(`select count(*)::int count,md5(coalesce(string_agg(to_jsonb(t)::text,'|' order by to_jsonb(t)::text),'')) hash from app.${t} t where auth_user_id=$1`,[owner]);result[t]=r.rows[0];}return result;}
describe('Safe Spend hosted-shaped PostgreSQL17 boundary (disposable only)',()=>{
  it('100 liquid accounts/cards/debts and 500 recurrences/goals use bounded batch reads, not N+1',async()=>{
    const c=await context(),ids=[c.account];
    for(let i=0;i<99;i++)ids.push((await finance.createAccount(c.owner,{name:'Cash '+i,type:'cash',currency:'BRL',initialBalanceMinor:'1000'})).id);
    for(let i=0;i<100;i++){
      await cards.create(c.owner,{displayName:'Card '+i,currency:'BRL',trackingStartDate:'2026-10-01',closingDay:28,dueDay:30},'UTC');
      await debts.create(c.owner,{name:'Debt '+i,debtType:'PERSONAL_LOAN',currency:'BRL',initialPrincipalMinor:'1000',trackingStartDate:'2026-10-01',rate:'0',ratePeriod:'EFFECTIVE_MONTHLY',minimumPaymentMinor:'100',dueDay:28},'2026-10-22',now);
    }
    await database.pool.query("insert into app.financial_goals(auth_user_id,name,currency,target_amount_minor,planned_monthly_minor,priority) select $1,'Goal '||n,'BRL',10000,100,'MEDIUM' from generate_series(1,500) n",[c.owner]);
    await database.pool.query("insert into app.financial_recurrences(auth_user_id,name,transaction_type,recurrence_kind,amount_minor,currency,frequency,interval_count,start_date) select $1,'Recurrence '||n,'EXPENSE','STANDARD',100,'BRL','MONTHLY',1,'2026-10-25'::date from generate_series(1,500) n",[c.owner]);
    await put(c,{accountIds:ids});
    const spy=vi.spyOn(pg.Client.prototype,'query'),started=performance.now();
    try{const v=await safeSpend.read(c.owner,'BRL',now);expect(v.accounts).toHaveLength(100);expect(v.debtCommitmentsMinor).toBe('10000');expect(v.goalReserveMinor).toBe('50000');expect(v.plannedRecurrenceReserveMinor).toBe('50000');expect(spy.mock.calls.length).toBeLessThanOrEqual(30);expect(spy.mock.calls.some(([q])=>String(typeof q==='string'?q:(q as {text?:string}).text).includes('read only'))).toBe(true);expect(performance.now()-started).toBeLessThan(5000);}finally{spy.mockRestore();}
  },30000);
  it('no automatic profile, config required, authenticated routes, strict payload',async()=>{const c=await context();expect((await request(c,'/settings?currency=BRL')).json()).toBe(null);await request(c,'?currency=BRL','GET',undefined,409);await request(c,'/settings','PUT',input(c,{ownerId:c.owner}),400);await request(c,'/settings','PUT',input(c,{accountIds:[]}),400);const r=await app.inject({url:'/api/v1/finance/safe-to-spend?currency=BRL'});expect(r.statusCode).toBe(401);});
  it('atomic settings, eligibility/currency checks, exact negative liquid balance',async()=>{const c=await context(),saved=await put(c);for(const type of ['credit','investment','debt'] as const){const a=await finance.createAccount(c.owner,{name:type,type,currency:'BRL',initialBalanceMinor:'0'});await request(c,'/settings','PUT',input(c,{accountIds:[a.id]}),400);}const usd=await finance.createAccount(c.owner,{name:'USD',type:'cash',currency:'USD',initialBalanceMinor:'1000'});await request(c,'/settings','PUT',input(c,{accountIds:[usd.id]}),400);const other=await context();await request(c,'/settings','PUT',input(c,{accountIds:[other.account]}),404);expect((await safeSpend.settings(c.owner,'BRL'))!.accountIds).toEqual(saved.accountIds);const negative=await finance.createAccount(c.owner,{name:'Negative',type:'other',currency:'BRL',initialBalanceMinor:'-100000'});await put(c,{accountIds:[c.account,negative.id]});const v=await view(c);expect(v.liquidFundsMinor).toBe('400000');expect(v.safeToSpendMinor).toBe('350000');expect(v.warnings).toContain('NEGATIVE_LIQUID_ACCOUNT');});
  it('Budget read model is a cap, no duplicate subtraction or auto budget creation',async()=>{const c=await context();await put(c,{safetyBufferMinor:'250000'});expect((await view(c)).safeToSpendMinor).toBe('250000');await budgets.ensurePeriod(c.owner,'2026-10','BRL','UTC');await budgets.putAllocation(c.owner,'2026-10',c.category,{currency:'BRL',amountMinor:'180000',rolloverPolicy:'NONE'});const v=await view(c);expect(v.budgetHeadroomMinor).toBe('180000');expect(v.safeToSpendMinor).toBe('180000');expect(v.cashCapacityMinor).toBe('250000');});
  it('archived card due commitment appears once, paid invoice excluded, future installments structural dedupe',async()=>{const c=await context();await put(c);const card=await cards.create(c.owner,{displayName:'Card fixture',currency:'BRL',trackingStartDate:'2026-10-01',closingDay:28,dueDay:30},'UTC');await cards.createPurchase(c.owner,card.id,{categoryId:c.category,description:'Card purchase',purchaseDate:'2026-10-22',totalAmountMinor:'300000',installmentCount:3,idempotencyKey:randomUUID()},'2026-10-22','UTC',now);await cards.archive(c.owner,card.id);let v=await view(c);expect(v.cardCommitmentsMinor).toBe('100000');expect(v.futureConfirmedExpensesMinor).toBe('0');expect(v.cashCapacityMinor).toBe('350000');await finance.createTransfer(c.owner,{sourceAccountId:c.account,destinationAccountId:card.accountId,amountMinor:'100000',currency:'BRL',description:'Payment',occurredAt:'2026-10-22T10:00:00Z',idempotencyKey:randomUUID()});v=await view(c);expect(v.cardCommitmentsMinor).toBe('0');expect(v.liquidFundsMinor).toBe('400000');});
  it('Debt term minimum and applicable actual payment; paid off has zero obligation',async()=>{const c=await context();await put(c);const d=await debts.create(c.owner,{name:'Debt',debtType:'PERSONAL_LOAN',currency:'BRL',initialPrincipalMinor:'100000',trackingStartDate:'2026-10-01',rate:'0',ratePeriod:'EFFECTIVE_MONTHLY',minimumPaymentMinor:'50000',dueDay:28},'2026-10-22',now);expect((await view(c)).debtCommitmentsMinor).toBe('50000');await debts.payment(c.owner,d.id,{sourceAccountId:c.account,principalAmountMinor:'10000',interestAmountMinor:'0',feeAmountMinor:'0',paidAt:'2026-10-21T10:00:00Z',idempotencyKey:randomUUID()},'2026-10-22','UTC',now);expect((await view(c)).debtCommitmentsMinor).toBe('40000');await debts.payment(c.owner,d.id,{sourceAccountId:c.account,principalAmountMinor:'90000',interestAmountMinor:'0',feeAmountMinor:'0',paidAt:'2026-10-22T10:00:00Z',idempotencyKey:randomUUID()},'2026-10-22','UTC',now);expect((await view(c)).debtCommitmentsMinor).toBe('0');});
  it('remaining Goal monthly plan uses actual net contribution, paused/archived/achieved excluded',async()=>{const c=await context();await put(c);const g=await goals.create(c.owner,{name:'Goal',currency:'BRL',targetAmountMinor:'200000',plannedMonthlyMinor:'100000',priority:'MEDIUM'});await goals.addEvent(c.owner,g.id,{type:'CONTRIBUTION',amountMinor:'40000',occurredAt:'2026-10-10T12:00:00Z',idempotencyKey:randomUUID()});expect((await view(c)).goalReserveMinor).toBe('60000');await goals.addEvent(c.owner,g.id,{type:'WITHDRAWAL',amountMinor:'10000',occurredAt:'2026-10-11T12:00:00Z',idempotencyKey:randomUUID()});expect((await view(c)).goalReserveMinor).toBe('70000');await goals.patch(c.owner,g.id,{status:'PAUSED'});expect((await view(c)).goalReserveMinor).toBe('0');await goals.patch(c.owner,g.id,{status:'ACTIVE',targetAmountMinor:'30000'});expect((await view(c)).goalReserveMinor).toBe('0');await goals.patch(c.owner,g.id,{status:'ARCHIVED'});expect((await view(c)).goalReserveMinor).toBe('0');});
  it('recurrence overlap remains conservative, expected income separate, existing 20 owner tables read-only',async()=>{const c=await context();await put(c);await finance.createTransaction(c.owner,{accountId:c.account,categoryId:c.category,type:'EXPENSE',currency:'BRL',description:'Future fixture',amountMinor:'30000',occurredAt:'2026-10-25T12:00:00Z'});await finance.createTransaction(c.owner,{accountId:c.account,type:'INCOME',currency:'BRL',description:'Expected fixture',amountMinor:'100000',occurredAt:'2026-10-26T12:00:00Z'});await recurrences.create(c.owner,{name:'Recurring fixture',transactionType:'EXPENSE',recurrenceKind:'STANDARD',amountMinor:'30000',currency:'BRL',categoryId:c.category,frequency:'MONTHLY',intervalCount:1,startDate:'2026-10-25'});const before=await ownSnapshot(c.owner),v=await view(c);expect(v.futureConfirmedExpensesMinor).toBe('30000');expect(v.plannedRecurrenceReserveMinor).toBe('30000');expect(v.safeToSpendMinor).toBe('390000');expect(v.safeToSpendWithExpectedIncomeMinor).toBe('490000');expect(v.warnings).toContain('POTENTIAL_RECURRENCE_OVERLAP');expect(await ownSnapshot(c.owner)).toEqual(before);await put(c,{reserveRecurrences:false});expect((await view(c)).safeToSpendMinor).toBe('420000');});
  it('separate currencies, profile timezone/DST month boundary, no FX',async()=>{const c=await context('America/Los_Angeles');await put(c);const a=await finance.createAccount(c.owner,{name:'USD cash',type:'cash',currency:'USD',initialBalanceMinor:'12345'});await put(c,{currency:'USD',accountIds:[a.id],safetyBufferMinor:'0'});const v=await safeSpend.read(c.owner,'BRL',new Date('2026-11-01T00:30:00Z'));expect(v.today).toBe('2026-10-31');expect(v.periodEndExclusive).toBe('2026-11-01');const summary=await safeSpend.summary(c.owner,now);expect(summary.map(v=>v.currency)).toEqual(['BRL','USD']);expect(summary[1]!.liquidFundsMinor).toBe('12345');});
  it('RLS A/B own SELECT, no public writes/delete, immutable owner/currency at DB boundary',async()=>{const a=await context(),b=await context(),s=await put(a);await database.db.transaction(async tx=>{await tx.execute(sql`select set_config('request.jwt.claim.sub',${b.owner},true)`);await tx.execute(sql`set local role authenticated`);const r=await tx.execute(sql`select id from app.financial_safe_spend_profiles where id=${s.id}::uuid`);expect(r.rows).toHaveLength(0);const update=await tx.execute(sql`update app.financial_safe_spend_profiles set safety_buffer_minor=0 where id=${s.id}::uuid returning id`);expect(update.rows).toHaveLength(0);const remove=await tx.execute(sql`delete from app.financial_safe_spend_profiles where id=${s.id}::uuid returning id`);expect(remove.rows).toHaveLength(0);});await database.db.transaction(async tx=>{await tx.execute(sql`select set_config('request.jwt.claim.sub',${a.owner},true)`);await tx.execute(sql`set local role authenticated`);expect((await tx.execute(sql`select id from app.financial_safe_spend_profiles where id=${s.id}::uuid`)).rows).toHaveLength(1);});await expect(database.pool.query('update app.financial_safe_spend_profiles set auth_user_id=$1 where id=$2',[b.owner,s.id])).rejects.toMatchObject({code:'23514'});expect(await safeSpend.settings(b.owner,'BRL')).toBe(null);});
});
afterAll(()=>app.close());
