import { randomUUID } from 'node:crypto';
import { afterAll,describe,it,expect } from 'vitest';
import { createDatabase } from '../../src/db/client.js';
import { loadConfig } from '../../src/config/env.js';
import { buildApp } from '../../src/app.js';
import { createProfileRepository } from '../../src/modules/profile/repository.js';
import { createFinanceRepository } from '../../src/modules/finance/repository.js';
import { createYieldRepository,createMarketRateCache } from '../../src/modules/finance/yield-repository.js';
import { BcbMarketRateProvider,MarketRateService } from '../../src/modules/finance/yield-market.js';
import { signingFixture,testEnv } from '../helpers.js';
import type { YieldProfile,YieldEstimate,YieldSummary } from '../../src/modules/finance/yield-contracts.js';
const config=loadConfig({...testEnv,RATE_LIMIT_MAX:'10000',TEST_DATABASE_URL:process.env.TEST_DATABASE_URL}),database=createDatabase(config),profiles=createProfileRepository(database),finance=createFinanceRepository(database),yieldRepo=createYieldRepository(database),fixture=await signingFixture(),clock=()=>new Date('2026-10-05T12:00:00Z');
const market=new MarketRateService(createMarketRateCache(database),new BcbMarketRateProvider(async()=>{throw new Error('External HTTP forbidden in integration tests');}),clock);
const app=await buildApp(config,{jwks:fixture.resolver,yieldClock:clock,dependencies:{profiles,finance,yield:yieldRepo,market,ping:database.ping,close:database.close}});
type Context={owner:string;headers:{authorization:string}};
async function context():Promise<Context>{const owner=randomUUID();await profiles.upsertForAuthUser(owner,{displayName:'Fixture',locale:'pt-BR',timezone:'America/Sao_Paulo'});return {owner,headers:{authorization:'Bearer '+await fixture.token({sub:owner})}};}
async function req<T>(c:Context,path:string,method:'GET'|'POST'='GET',payload?:unknown,status=method==='POST'?201:200):Promise<T>{const r=await app.inject({method,url:'/api/v1/finance'+path,headers:c.headers,...(payload?{payload:payload as Record<string,unknown>}:{})});expect(r.statusCode,r.body).toBe(status);return r.json<T>();}
const input={ruleType:'FIXED_RATE',effectiveFrom:'2026-10-05',fixedRate:'0.10',ratePeriod:'ANNUAL',dayCountConvention:'CALENDAR_365',taxTreatment:'NONE'};
async function account(c:Context,currency:'BRL'|'USD'='BRL',amount='100000'){return finance.createAccount(c.owner,{name:'Yield fixture',type:'checking',currency,initialBalanceMinor:amount});}
const path=(id:string)=>'/accounts/'+id+'/yield-profile';
const create=(c:Context,id:string,extra={},status=201)=>req<YieldProfile>(c,path(id),'POST',{...input,...extra},status);
afterAll(()=>app.close());
describe('yield PostgreSQL17 API/integrity/RLS',()=>{
 it('atomic profile, exact projection, version history and archive retain history',async()=>{const c=await context(),a=await account(c);await create(c,a.id);const e=await req<YieldEstimate>(c,`/accounts/${a.id}/yield/estimate?to=2027-10-05`);expect(e.grossValueMinor).toBe('110000');const next=await req<YieldProfile>(c,path(a.id)+'/versions','POST',{...input,effectiveFrom:'2026-10-06',fixedRate:'0.115'});expect(next.rules).toHaveLength(2);expect(next.rules[0]?.fixedRate).toBe('0.1');expect(next.rules[0]?.effectiveTo).toBe('2026-10-06');await req(c,path(a.id)+'/archive','POST',{},200);await req(c,`/accounts/${a.id}/yield/estimate?to=2027-10-05`,'GET',undefined,409);expect((await req<YieldProfile>(c,path(a.id)+'/history')).rules).toHaveLength(2);await req(c,path(a.id)+'/versions','POST',{...input,effectiveFrom:'2026-10-07'},409);});
 it('cross-owner404 on get/create/version/history/archive/estimate',async()=>{const a=await context(),b=await context(),acct=await account(a);await create(a,acct.id);for(const [p,method,payload] of [[path(acct.id),'GET',undefined],[path(acct.id),'POST',input],[path(acct.id)+'/versions','POST',{...input,effectiveFrom:'2026-10-06'}],[path(acct.id)+'/history','GET',undefined],[path(acct.id)+'/archive','POST',{}],[`/accounts/${acct.id}/yield/estimate?to=2027-10-05`,'GET',undefined]] as const)await req(b,p,method,payload,404);expect(await req(b,'/yield/profiles')).toEqual([]);});
 it('strict contracts prevent owner spoofing/DELETE/market writes; invalid rule rolls back',async()=>{const c=await context(),a=await account(c);for(const extra of [{ownerId:randomUUID()},{fixedRate:null},{fixedRate:'10.1'},{dayCountConvention:'MONTHLY_ANNIVERSARY'},{effectiveFrom:'2026-02-30'}])await create(c,a.id,extra,400);expect(await req(c,path(a.id))).toBeNull();await create(c,a.id);await create(c,a.id,{},409);expect((await app.inject({method:'DELETE',url:'/api/v1/finance'+path(a.id),headers:c.headers})).statusCode).toBe(404);await req(c,'/yield/benchmarks','POST',{value:'10'},404);});
 it('chronological future version changes cannot rewrite history; duplicate concurrent version gets one result',async()=>{const c=await context(),a=await account(c);await create(c,a.id,{effectiveFrom:'2026-01-01'});await req(c,path(a.id)+'/versions','POST',{...input,effectiveFrom:'2026-04-01'},400);const attempts=await Promise.all(['0.11','0.12'].map(fixedRate=>app.inject({method:'POST',url:'/api/v1/finance'+path(a.id)+'/versions',headers:c.headers,payload:{...input,effectiveFrom:'2026-10-06',fixedRate}})));expect(attempts.map(r=>r.statusCode).sort()).toEqual([201,400]);expect((await req<YieldProfile>(c,path(a.id))).rules).toHaveLength(2);});
 it('USD benchmark rejected, USD fixed valid; BRL/USD totals separated',async()=>{const c=await context(),b=await account(c),u=await account(c,'USD');await create(c,u.id,{ruleType:'BENCHMARK_PERCENTAGE',fixedRate:null,ratePeriod:null,benchmark:'CDI',benchmarkPercentage:'1',dayCountConvention:'BUSINESS_252'},400);await create(c,b.id);await create(c,u.id);const s=await req<YieldSummary>(c,'/yield/summary?to=2027-10-05');expect(s.totals.map(t=>t.currency)).toEqual(['BRL','USD']);expect(s.totals.every(t=>t.estimatedGrossYieldMinor==='10000')).toBe(true);});
 it('negative balance zero, inactive projection conflict, history retained',async()=>{const c=await context(),a=await account(c,'BRL','-100');await create(c,a.id);expect((await req<YieldEstimate>(c,`/accounts/${a.id}/yield/estimate?to=2027-10-05`)).grossYieldMinor).toBe('0');await finance.patchAccount(c.owner,a.id,{isActive:false});await req(c,`/accounts/${a.id}/yield/estimate?to=2027-10-05`,'GET',undefined,409);expect((await req<YieldEstimate>(c,`/accounts/${a.id}/yield/estimate?from=2026-10-01&to=2026-10-05`)).status).toBe('AVAILABLE');});
 it('historical minimum excludes cancelled/future transfers and deposits never raise minimum',async()=>{const c=await context(),a=await account(c),b=await account(c);await database.pool.query("update app.financial_accounts set created_at='2026-01-01T03:00:00Z' where auth_user_id=$1",[c.owner]);await create(c,a.id,{effectiveFrom:'2026-01-01',ruleType:'SAVINGS_BR',fixedRate:null,ratePeriod:null,dayCountConvention:'MONTHLY_ANNIVERSARY',taxTreatment:'BR_SAVINGS_EXEMPT'});await database.pool.query("insert into app.financial_transactions(auth_user_id,account_id,type,amount_minor,currency,description,occurred_at,is_cancelled) values($1,$2,'EXPENSE',50000,'BRL','Fixture','2026-01-15T12:00:00Z',false),($1,$2,'INCOME',50000,'BRL','Fixture','2026-01-20T12:00:00Z',false),($1,$2,'EXPENSE',99999,'BRL','Fixture','2026-01-10',true)",[c.owner,a.id]);await database.pool.query("insert into app.financial_transfers(auth_user_id,source_account_id,destination_account_id,amount_minor,currency,description,occurred_at,idempotency_key,is_cancelled) values($1,$2,$3,99999,'BRL','Fixture','2026-01-05',$4,true),($1,$2,$3,99999,'BRL','Fixture','2027-01-05',$5,false)",[c.owner,a.id,b.id,randomUUID(),randomUUID()]);const cache=createMarketRateCache(database);await cache.write('432',['2025-12-01','2026-01-01','2026-02-01'].map(date=>({date,value:'0.15'})),'2026-01-01T00:00:00Z');await cache.write('226',['2025-12-01','2026-01-01','2026-02-01'].map(date=>({date,value:'0'})),'2026-01-01T00:00:00Z');const e=await req<YieldEstimate>(c,`/accounts/${a.id}/yield/estimate?from=2026-01-01&to=2026-02-01`);expect(e.grossYieldMinor).toBe('250');expect(e.sourceStatus).toBe('STALE');});
 it('RLS owns SELECT/INSERT/profileUPDATE, denies ruleUPDATE/DELETE, market access and spoofing',async()=>{const a=await context(),b=await context(),acct=await account(a),p=await create(a,acct.id),client=await database.pool.connect();const start=async(owner:string)=>{await client.query('begin');await client.query('set local role authenticated');await client.query("select set_config('request.jwt.claim.sub',$1,true)",[owner]);};try{await start(b.owner);expect((await client.query('select id from app.financial_yield_profiles where id=$1',[p.id])).rows).toHaveLength(0);expect((await client.query('select id from app.financial_yield_rules where profile_id=$1',[p.id])).rows).toHaveLength(0);expect((await client.query("update app.financial_yield_profiles set status='ARCHIVED' where id=$1 returning id",[p.id])).rows).toHaveLength(0);await client.query('rollback');await start(a.owner);expect((await client.query('select id from app.financial_yield_profiles where id=$1',[p.id])).rows).toHaveLength(1);expect((await client.query('update app.financial_yield_rules set fixed_rate=1 where profile_id=$1 returning id',[p.id])).rows).toHaveLength(0);expect((await client.query('delete from app.financial_yield_profiles where id=$1 returning id',[p.id])).rows).toHaveLength(0);expect((await client.query('delete from app.financial_yield_rules where profile_id=$1 returning id',[p.id])).rows).toHaveLength(0);expect((await client.query('select id from app.financial_market_rates')).rows).toHaveLength(0);await expect(client.query("insert into app.financial_market_rates(benchmark,series_code,rate_date,rate_value,rate_unit) values('CDI','12','2026-10-01',0.001,'DAILY_DECIMAL')")).rejects.toMatchObject({code:'42501'});await client.query('rollback');await start(a.owner);const foreign=await account(b);await expect(client.query("insert into app.financial_yield_profiles(auth_user_id,account_id,currency) values($1,$2,'BRL')",[a.owner,foreign.id])).rejects.toMatchObject({code:'23503'});}finally{await client.query('rollback');client.release();}});
 it('DB trigger rejects overlapping ranges and immutable edits',async()=>{const c=await context(),a=await account(c),p=await create(c,a.id);await expect(database.pool.query("update app.financial_yield_rules set fixed_rate=0.9 where profile_id=$1",[p.id])).rejects.toMatchObject({code:'23514'});await expect(database.pool.query("insert into app.financial_yield_rules(auth_user_id,profile_id,rule_type,effective_from,fixed_rate,rate_period,day_count_convention,tax_treatment) values($1,$2,'FIXED_RATE','2026-10-06',0.1,'ANNUAL','CALENDAR_365','NONE')",[c.owner,p.id])).rejects.toMatchObject({code:'23514'});});
 it('DB rejects missing fixed/benchmark fields even when SQL CHECK evaluates NULL',async()=>{
  const c=await context(),a=await account(c);
  const p=(await database.pool.query("insert into app.financial_yield_profiles(auth_user_id,account_id,currency) values($1,$2,'BRL') returning id",[c.owner,a.id])).rows[0];
  for(const fields of ["'FIXED_RATE',NULL,NULL,NULL,'ANNUAL','CALENDAR_365'","'FIXED_RATE',NULL,0.1,NULL,NULL,'CALENDAR_365'","'BENCHMARK_PERCENTAGE','CDI',NULL,NULL,NULL,'BUSINESS_252'","'BENCHMARK_PERCENTAGE',NULL,NULL,1,NULL,'BUSINESS_252'"])
    await expect(database.pool.query("insert into app.financial_yield_rules(auth_user_id,profile_id,effective_from,rule_type,benchmark,fixed_rate,benchmark_percentage,rate_period,day_count_convention,tax_treatment) values($1,$2,'2026-10-05',"+fields+",'NONE')",[c.owner,p.id])).rejects.toMatchObject({code:'23514'});
  expect((await database.pool.query('select id from app.financial_yield_rules where profile_id=$1',[p.id])).rows).toHaveLength(0);
 });
 it('authenticated owner can insert first rule, while foreign owner and anon cannot',async()=>{
  const a=await context(),b=await context(),acct=await account(a),client=await database.pool.connect();
  const p=(await database.pool.query("insert into app.financial_yield_profiles(auth_user_id,account_id,currency) values($1,$2,'BRL') returning id",[a.owner,acct.id])).rows[0];
  const insert="insert into app.financial_yield_rules(auth_user_id,profile_id,rule_type,effective_from,day_count_convention,tax_treatment) values($1,$2,'ZERO','2026-10-05','CALENDAR_365','NONE') returning id";
  try{
    await client.query('begin');await client.query('set local role authenticated');await client.query("select set_config('request.jwt.claim.sub',$1,true)",[a.owner]);
    expect((await client.query(insert,[a.owner,p.id])).rows).toHaveLength(1);await client.query('commit');
    await client.query('begin');await client.query('set local role authenticated');await client.query("select set_config('request.jwt.claim.sub',$1,true)",[b.owner]);
    // The invoker trigger sees no foreign profile through RLS and rejects first.
    await expect(client.query(insert,[b.owner,p.id])).rejects.toMatchObject({code:'23503'});await client.query('rollback');
    await client.query('begin');await client.query('set local role anon');
    expect((await client.query('select id from app.financial_yield_profiles')).rows).toHaveLength(0);
    expect((await client.query('select id from app.financial_yield_rules')).rows).toHaveLength(0);
    await expect(client.query(insert,[a.owner,p.id])).rejects.toMatchObject({code:'23503'});
  }finally{await client.query('rollback');client.release();}
 });
 it('all earlier tables hashed before/after projections, configuration, comparison and archive',async()=>{const c=await context(),a=await account(c);const tables=['profiles','financial_accounts','financial_categories','financial_transactions','financial_transfers','financial_budget_periods','financial_budget_allocations','financial_goals','financial_goal_events','financial_recurrences','financial_net_worth_items','financial_net_worth_valuations'];const snapshot=()=>Promise.all(tables.map(async table=>(await database.pool.query("select md5(coalesce(jsonb_agg(to_jsonb(t) order by id)::text,'[]')) h from app."+table+' t where auth_user_id=$1',[c.owner])).rows[0]?.h));const before=await snapshot();await create(c,a.id);await req(c,`/accounts/${a.id}/yield/estimate?to=2027-10-05`);await req(c,'/yield/comparison','POST',{currency:'BRL',principalMinor:'100000',from:'2026-10-05',to:'2027-10-05',fixedRate:'0.1',ratePeriod:'ANNUAL',taxTreatment:'NONE'},200);await req(c,path(a.id)+'/archive','POST',{},200);expect(await snapshot()).toEqual(before);});
});
