import { writeFile, mkdir, readFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { createHash } from 'node:crypto';
import * as contracts from '../src/modules/finance/contracts.js';
import { currencyDigits } from '../src/modules/finance/domain.js';

// Deterministic build artifact, not a second hand-written API contract.
type Schema = {
  const?: unknown;
  type?: string;
  anyOf?: Schema[];
  properties?: Record<string, Schema>;
  required?: string[] | undefined;
  items?: Schema;
  format?: string;
  pattern?: string;
  minLength?: number;
  maxLength?: number;
  minProperties?: number;
};
function zod(schema: Schema): string {
  if ('const' in schema) return `z.literal(${JSON.stringify(schema.const)})`;
  if (schema.anyOf) return `z.union([${schema.anyOf.map(zod).join(', ')}])`;
  if (schema.type === 'null') return 'z.null()';
  if (schema.type === 'boolean') return 'z.boolean()';
  if (schema.type === 'array') return `z.array(${zod(schema.items!)})`;
  if (schema.type === 'object')
    return (
      `z.object({ ${Object.entries(schema.properties!)
        .map(
          ([key, value]) =>
            `${key}: ${zod(value)}${schema.required?.includes(key) ? '' : '.optional()'}`,
        )
        .join(', ')} }).strict()` +
      (schema.minProperties
        ? `.refine(value => Object.keys(value).length >= ${schema.minProperties})`
        : '')
    );
  if (schema.type === 'string')
    return (
      'z.string()' +
      (schema.format === 'uuid'
        ? '.uuid()'
        : schema.format === 'date-time'
          ? '.datetime({ offset: true })'
          : '') +
      (schema.pattern ? `.regex(new RegExp(${JSON.stringify(schema.pattern)}))` : '') +
      (schema.minLength !== undefined ? `.min(${schema.minLength})` : '') +
      (schema.maxLength !== undefined ? `.max(${schema.maxLength})` : '')
    );
  throw new Error('Unsupported Finance schema');
}
const source = JSON.stringify({ contracts, currencyDigits });
const output =
  '// Generated by Back/scripts/finance-contract.ts; edit the Back TypeBox source, not this file.\n' +
  `// Source SHA256: ${createHash('sha256').update(source).digest('hex')}\nimport { z } from 'zod';\n` +
  `export const currencyDigits = ${JSON.stringify(currencyDigits)} as const;\n` +
  Object.entries(contracts)
    .map(
      ([key, schema]) =>
        `export const ${key}Schema = ${zod(schema)};\nexport type ${key} = z.infer<typeof ${key}Schema>;\n`,
    )
    .join('');
const path =
  process.argv.find((arg) => arg.startsWith('--output='))?.slice(9) ?? 'openapi/finance-client.ts';
if (process.argv.includes('--check')) {
  if ((await readFile(path, 'utf8')) !== output) throw new Error('Finance contract drift');
} else {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, output);
}
process.stdout.write('Finance client contract generated/verified.\n');
