import { writeFile, mkdir, readFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { createHash } from 'node:crypto';
import * as contracts from '../src/modules/finance/contracts.js';
import * as budgetContracts from '../src/modules/finance/budget-contracts.js';
import * as goalContracts from '../src/modules/finance/goal-contracts.js';
import * as recurrenceContracts from '../src/modules/finance/recurrence-contracts.js';
import * as netWorthContracts from '../src/modules/finance/net-worth-contracts.js';
import * as yieldContracts from '../src/modules/finance/yield-contracts.js';
import * as cardContracts from '../src/modules/finance/card-contracts.js';
import * as debtContracts from '../src/modules/finance/debt-contracts.js';
import * as safeSpendContracts from '../src/modules/finance/safe-spend-contracts.js';
import { currencyDigits } from '../src/modules/finance/domain.js';

// Deterministic build artifact, not a second hand-written API contract.
type Schema = {
  const?: unknown;
  type?: string;
  anyOf?: Schema[];
  properties?: Record<string, Schema>;
  required?: string[] | undefined;
  items?: Schema;
  format?: string;
  pattern?: string;
  minLength?: number;
  maxLength?: number;
  minProperties?: number;
  minimum?: number;
  maximum?: number;
  minItems?: number;
  maxItems?: number;
  uniqueItems?: boolean;
};
function zod(schema: Schema): string {
  if ('const' in schema) return `z.literal(${JSON.stringify(schema.const)})`;
  if (schema.anyOf) return `z.union([${schema.anyOf.map(zod).join(', ')}])`;
  if (schema.type === 'null') return 'z.null()';
  if (schema.type === 'boolean') return 'z.boolean()';
  if (schema.type === 'number' || schema.type === 'integer') return 'z.number()' + (schema.type === 'integer' ? '.int()' : '') + (schema.minimum !== undefined ? `.min(${schema.minimum})` : '') + (schema.maximum !== undefined ? `.max(${schema.maximum})` : '');
  if (schema.type === 'array') return `z.array(${zod(schema.items!)})` + (schema.minItems !== undefined ? `.min(${schema.minItems})` : '') + (schema.maxItems !== undefined ? `.max(${schema.maxItems})` : '') + (schema.uniqueItems ? '.refine(values => new Set(values).size === values.length)' : '');
  if (schema.type === 'object')
    return (
      `z.object({ ${Object.entries(schema.properties!)
        .map(
          ([key, value]) =>
            `${key}: ${zod(value)}${schema.required?.includes(key) ? '' : '.optional()'}`,
        )
        .join(', ')} }).strict()` +
      (schema.minProperties
        ? `.refine(value => Object.keys(value).length >= ${schema.minProperties})`
        : '')
    );
  if (schema.type === 'string')
    return (
      'z.string()' +
      (schema.format === 'uuid'
        ? '.uuid()'
        : schema.format === 'date-time'
          ? '.datetime({ offset: true })'
          : schema.format === 'date' ? '.regex(/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/)' : '') +
      (schema.pattern ? `.regex(new RegExp(${JSON.stringify(schema.pattern)}))` : '') +
      (schema.minLength !== undefined ? `.min(${schema.minLength})` : '') +
      (schema.maxLength !== undefined ? `.max(${schema.maxLength})` : '')
    );
  throw new Error('Unsupported Finance schema');
}
const prefixedDebts = Object.fromEntries(Object.entries(debtContracts).map(([key,value]) => [key.startsWith('Debt') ? key : 'Debt'+key,value]));
const allContracts = { ...contracts, ...budgetContracts, ...goalContracts, ...recurrenceContracts, ...netWorthContracts,...yieldContracts,...cardContracts,...prefixedDebts,...safeSpendContracts };
const source = JSON.stringify({ contracts: allContracts, currencyDigits });
const output =
  '// Generated by Back/scripts/finance-contract.ts; edit the Back TypeBox source, not this file.\n' +
  `// Source SHA256: ${createHash('sha256').update(source).digest('hex')}\nimport { z } from 'zod';\n` +
  `export const currencyDigits = ${JSON.stringify(currencyDigits)} as const;\n` +
  Object.entries(allContracts)
    .map(
      ([key, schema]) =>
        `export const ${key}Schema = ${zod(schema)};\nexport type ${key} = z.infer<typeof ${key}Schema>;\n`,
    )
    .join('');
const path =
  process.argv.find((arg) => arg.startsWith('--output='))?.slice(9) ?? 'openapi/finance-client.ts';
if (process.argv.includes('--check')) {
  if ((await readFile(path, 'utf8')) !== output) throw new Error('Finance contract drift');
} else {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, output);
}
process.stdout.write('Finance client contract generated/verified.\n');
