import { describe,it,expect } from 'vitest';
import { calculateSafeSpend,type SafeSpendSnapshot } from '../../src/modules/finance/safe-spend-domain.js';
import { recurrenceToday,civilOrdinal } from '../../src/modules/finance/recurrence-domain.js';
import { anchorMonth,cardView,type CardSnapshot } from '../../src/modules/finance/card-domain.js';
import type { Account } from '../../src/modules/finance/contracts.js';
import type { BudgetSummary } from '../../src/modules/finance/budget-contracts.js';
import type { Card,Purchase,BillingRule } from '../../src/modules/finance/card-contracts.js';
import type { RecurrenceRecord } from '../../src/modules/finance/recurrence-domain.js';
const account:Account={id:'11111111-1111-4111-8111-111111111111',name:'Liquid',type:'checking',currency:'BRL',initialBalanceMinor:'500000',balanceMinor:'500000',isActive:true,createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z'};
function input(extra:Partial<SafeSpendSnapshot>={}):SafeSpendSnapshot{return {settings:{id:account.id,currency:'BRL',accountIds:[account.id],safetyBufferMinor:'50000',respectBudget:true,reserveRecurrences:true,reserveGoalPlans:true,createdAt:account.createdAt,updatedAt:account.updatedAt},accounts:[account],cards:[],debts:[],goals:[],recurrences:[],future:[],budget:{periodId:null,budgetedTotalMinor:'0',expenseTotalMinor:'0'} as BudgetSummary,today:'2026-10-22',end:'2026-11-01',zone:'UTC',now:new Date('2026-10-22T12:00:00Z'),...extra};}
function card(payments='0',archived=false){const c={id:account.id,accountId:account.id,currency:'BRL',displayName:'Card',trackingStartDate:'2026-01-01',creditLimitMinor:null,status:archived?'ARCHIVED':'ACTIVE'} as Card;
  const rule={id:account.id,cardId:c.id,effectiveFrom:'2026-01-01',effectiveTo:null,closingDay:28,dueDay:30} as BillingRule;
  const p={id:account.id,cardId:c.id,description:'Purchase',status:'ACTIVE',installmentCount:1,installments:[{id:account.id,transactionId:account.id,scheduledDate:'2026-10-22',amountMinor:'100000',installmentNumber:1}]} as Purchase;
  return cardView({card:c,rules:[rule],purchases:[p],realBalanceMinor:String(-100000n+BigInt(payments)),legacyBalanceMinor:'0',inboundPaymentsMinor:payments} satisfies CardSnapshot,'2026-10-22','UTC');}
const recurring={id:account.id,name:'Plan',startDate:'2026-10-22',endDate:null,frequency:'MONTHLY',intervalCount:1,status:'ACTIVE',transactionType:'EXPENSE',currency:'BRL',amountMinor:'30000',accountId:null,categoryId:null} as RecurrenceRecord;
describe('Safe to Spend exact conservative model',()=>{
  it('basic liquid less buffer; no auto-budget; floor daily pace',()=>{const r=calculateSafeSpend(input());expect(r.liquidFundsMinor).toBe('500000');expect(r.safeToSpendMinor).toBe('450000');expect(r.dailySafeToSpendMinor).toBe('45000');expect(r.warnings).toContain('NO_BUDGET_FOR_CURRENT_MONTH');});
  it('card invoice is counted exactly once, structural installment excluded',()=>{const r=calculateSafeSpend(input({cards:[card()],future:[{id:account.id,type:'EXPENSE',date:'2026-10-22',amount:'100000',description:'Card expense',categoryId:null,accountId:account.id,linked:true}]}));expect(r.cashCapacityMinor).toBe('350000');expect(r.futureConfirmedExpensesMinor).toBe('0');expect(r.items.find(i=>i.sourceType==='FUTURE_EXPENSE')!.included).toBe(false);});
  it('paid card reserves zero; archived card retains obligation',()=>{expect(calculateSafeSpend(input({cards:[card('100000')]})).cardCommitmentsMinor).toBe('0');expect(calculateSafeSpend(input({cards:[card('0',true)]})).cardCommitmentsMinor).toBe('100000');});
  it('future invoice credit subtracts scheduled commitment once',()=>{const v=card('150000');v.invoices[0]!.scheduledChargesMinor='60000';v.invoices[0]!.committedTotalMinor='160000';expect(calculateSafeSpend(input({cards:[v]})).cardCommitmentsMinor).toBe('10000');});
  it('debt declared minimum less applicable real payments; no writes',()=>{const r=calculateSafeSpend(input({cards:[card()],debts:[{id:account.id,name:'Debt',due:'2026-10-28',minimum:'50000',paid:'0'}]}));expect(r.cashCapacityMinor).toBe('300000');expect(calculateSafeSpend(input({debts:[{id:account.id,name:'Debt',due:'2026-10-28',minimum:'50000',paid:'20000'}]})).debtCommitmentsMinor).toBe('30000');});
  it('recurrences toggle reserve; overlap warns without deleting either source',()=>{const i=input({recurrences:[recurring],future:[{id:account.id,type:'EXPENSE',date:'2026-10-22',amount:'30000',description:'Same plan',categoryId:null,accountId:account.id,linked:false}]});let r=calculateSafeSpend(i);expect(r.plannedRecurrenceReserveMinor).toBe('30000');expect(r.hardCommitmentsMinor).toBe('30000');expect(r.warnings).toContain('POTENTIAL_RECURRENCE_OVERLAP');i.settings.reserveRecurrences=false;r=calculateSafeSpend(i);expect(r.plannedRecurrenceReserveMinor).toBe('0');expect(r.projectedRecurrenceExpensesMinor).toBe('30000');});
  it.each([['40000','60000'],['20000','80000'],['-10000','100000']])('goal monthly net %s -> reserve %s',(contributed,expected)=>{expect(calculateSafeSpend(input({goals:[{id:account.id,name:'Goal',planned:'100000',contributed,achieved:false}]})).goalReserveMinor).toBe(expected);});
  it('achieved goal reserve zero; goal plan toggle excludes, not subtract current goal amount',()=>{const i=input({goals:[{id:account.id,name:'Goal',planned:'100000',contributed:'0',achieved:true}]});expect(calculateSafeSpend(i).goalReserveMinor).toBe('0');i.goals[0]!.achieved=false;i.settings.reserveGoalPlans=false;expect(calculateSafeSpend(i).goalReserveMinor).toBe('0');});
  it.each([['180000','180000'],['400000','250000'],['-20000','0']])('budget %s is cap, never subtraction',(headroom,expected)=>{const i=input({budget:{periodId:account.id,budgetedTotalMinor:headroom,expenseTotalMinor:'0'} as BudgetSummary});i.settings.safetyBufferMinor='250000';expect(calculateSafeSpend(i).safeToSpendMinor).toBe(expected);});
  it('negative capacity floors headline but preserves signed shortfall',()=>{const i=input({accounts:[{...account,balanceMinor:'100000'}]});i.settings.safetyBufferMinor='150000';const r=calculateSafeSpend(i);expect(r.cashCapacityMinor).toBe('-50000');expect(r.shortfallMinor).toBe('50000');expect(r.status).toBe('OVERCOMMITTED');});
  it('expected income scenario isolated, cap respected, received income absent',()=>{const r=calculateSafeSpend(input({future:[{id:account.id,type:'INCOME',date:'2026-10-30',amount:'100000',description:'Expected',categoryId:null,accountId:account.id,linked:false}]}));expect(r.safeToSpendMinor).toBe('450000');expect(r.safeToSpendWithExpectedIncomeMinor).toBe('550000');});
  it('negative selected balance is summed, not clamped',()=>{expect(calculateSafeSpend(input({accounts:[account,{...account,id:'negative',balanceMinor:'-100000'}]})).liquidFundsMinor).toBe('400000');});
  it.each(['JPY','KWD','USD'] as const)('integer units have no /100 currency assumption: %s',currency=>{const i=input();i.settings.currency=currency;i.settings.safetyBufferMinor='0';i.accounts[0]={...account,currency,balanceMinor:'100001'};const r=calculateSafeSpend(i);expect(r.safeToSpendMinor).toBe('100001');expect(r.dailySafeToSpendMinor).toBe('10000');});
  it.each([['America/Los_Angeles','2026-11-01T00:30:00Z','2026-10-31'],['America/New_York','2026-11-01T05:30:00Z','2026-11-01'],['Pacific/Auckland','2026-10-31T12:30:00Z','2026-11-01']])('civil month and DST: %s',(zone,instant,today)=>{expect(recurrenceToday(zone,new Date(instant))).toBe(today);const end=anchorMonth(today.slice(0,7)+'-01',1,1);expect(civilOrdinal(end)-civilOrdinal(today)).toBeGreaterThan(0);});
  it('pure reads never mutate input or any source balances',()=>{const s=input({cards:[card()]});const before=JSON.stringify(s);calculateSafeSpend(s);expect(JSON.stringify(s)).toBe(before);});
  it('earlier-today expense warns about recurrence overlap without subtracting cash twice',()=>{const r=calculateSafeSpend(input({recurrences:[recurring],knownExpenses:[{amount:'30000',date:'2026-10-22',categoryId:null}]}));expect(r.futureConfirmedExpensesMinor).toBe('0');expect(r.plannedRecurrenceReserveMinor).toBe('30000');expect(r.warnings).toContain('POTENTIAL_RECURRENCE_OVERLAP');});
});
